### ISSUE TITLE
Aggregate country level by setting the rest of the data to null

### ISSUE THREAD

**Issue by stevenqzhang** [covidatlas/coronadatascraper#148] opened 2020-03-19 16:27 UTC
Here's a suggestion:

We could have aggregate country-level data already done, if all the sub-fields are null

What I mean is:

Currently, for Italy, if county/city/state are all null, then the Country=italy rows give aggregate data for all the dates.

For China and US, however, that is not the case.

It would be great to backfill them (and/or write documentation on this effect) to "normalize" the dataset

**Comment by lazd** [comment] 2020-03-19 17:07
@stevenqzhang absolutely. Right now, we manually make calls to `transform.sumData(regions)` to get a sum for the entire region. This is something that could be done once we're all done, totally automatically.

We discussed this earlier on slack: https://sars-cov-2covid-19.slack.com/archives/CV0MMQDRQ/p1584611369321800

**Comment by Wikunia** [comment] 2020-03-19 17:14
There is another issue with Australia where there are only two entries for country level Australia.
It would be nice to have get country level by setting the others level to NULL and the same for state level and county level. 
This produces some extra rows but will be easier to parse. I'm very new to this repo but I think something like this has been done to decide which source is used already.

**Comment by Wikunia** [comment] 2020-03-19 17:28
Another option would be to just always use the city level if available then county and state and the country level.
Then one can simply aggregate over the required level.

**Comment by Wikunia** [comment] 2020-03-20 09:40
Otherwise we would introduce errors like the county level does not sum up to state level.
If there is state level data then we don't need country level data as it should be matching anyway. It would also reduce the size of the csv even though this is not important atm.

**Comment by Wikunia** [comment] 2020-03-20 12:37
This is the one thing breaking my visualization. If a decision is made about how to aggregate the data I can have a look into this and then use the data for my visualization.

**Comment by jzohrab** [comment] 2020-08-09 15:21
This issue isn't really applicable in the new project (Li).  We do have a "don't use sumData in Li" issue (https://github.com/covidatlas/li/issues/51), which I'd like to get rolling.  I had started something similar in a wip PR, "add report rollups", https://github.com/covidatlas/li/pull/260, but it's tricky.

Closing this as it's effectively a duplicate of the PR.  Thanks, cheers! jz

**Closed by jzohrab** 2020-08-09 15:21 UTC
